# Generated by Django 4.2.1 on 2023-06-12 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_degree_alter_user_district_alter_user_dob_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_la', models.CharField(max_length=30)),
                ('name_en', models.CharField(max_length=30)),
                ('credit', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_no', models.CharField(max_length=15)),
                ('name_la', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TermScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
                ('term', models.CharField(max_length=10)),
                ('sum_credit', models.FloatField(default=0)),
                ('gpa', models.FloatField(default=0)),
                ('ps', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeachDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.IntegerField(default=0)),
                ('s_check', models.FloatField(default=0)),
                ('s_test', models.FloatField(default=0)),
                ('s_homework', models.FloatField(default=0)),
                ('s_activity', models.FloatField(default=0)),
                ('s_project', models.FloatField(default=0)),
                ('s_midterm', models.FloatField(default=0)),
                ('s_final', models.FloatField(default=0)),
                ('s_total', models.FloatField(default=0)),
                ('s_grade', models.FloatField(default=0)),
                ('sum_credit', models.FloatField(default=0)),
                ('grade', models.CharField(max_length=5)),
                ('ps', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.course')),
                ('term_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.termscore')),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_no', models.CharField(max_length=15)),
                ('name_la', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.major')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.classroom'),
        ),
        migrations.AddField(
            model_name='user',
            name='major',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.major'),
        ),
    ]
