# Generated by Django 4.2.1 on 2023-06-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_course_department_termscore_teachdetail_scoredetail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dep_no',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='major',
            name='major_no',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='scoredetail',
            name='s_grade',
            field=models.FloatField(db_column='s_gpa', default=0),
        ),
    ]
