# Generated by Django 4.2.1 on 2023-06-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_department_dep_no_alter_major_major_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoredetail',
            name='s_grade',
            field=models.FloatField(default=0, verbose_name='s_gpa'),
        ),
    ]
