# Generated by Django 4.2.1 on 2023-06-20 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_scoredetail_s_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoredetail',
            name='teach_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scoredetail',
            name='grade',
            field=models.CharField(editable=False, max_length=5),
        ),
        migrations.AlterField(
            model_name='scoredetail',
            name='s_grade',
            field=models.FloatField(default=0, editable=False, verbose_name='s_gpa'),
        ),
        migrations.AlterField(
            model_name='scoredetail',
            name='s_total',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='scoredetail',
            name='sum_credit',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
